plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    id("jacoco") //Enable the JaCoCo Plugin
}

jacoco {
    toolVersion = "0.8.14" //Defines which JaCoCo version will be used
}

android {
    namespace = "app.cryptoseal"
    compileSdk = 36

    defaultConfig {
        applicationId = "app.cryptoseal"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            enableUnitTestCoverage = true
            enableAndroidTestCoverage = true
        }
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }
    packaging {
        resources {
            excludes += "/META-INF/LICENSE.md"
            excludes += "/META-INF/LICENSE-notice.md"
            excludes += "/META-INF/AL2.0"
            excludes += "/META-INF/LGPL2.1"
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.compose.material.icons.extended)

    implementation(libs.gson)
    implementation(libs.androidx.security.crypto)
    implementation(libs.androidx.camera.core)
    implementation(libs.androidx.camera.camera2)
    implementation(libs.androidx.camera.lifecycle)
    implementation(libs.androidx.camera.view)
    implementation(libs.barcode.scanning)
    implementation(libs.play.services.location)
    implementation(libs.zxing.core)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}

// Create a custom JaCoCo report task
tasks.register<JacocoReport>("jacocoTestReport") {

    // Run BOTH test types before generating report
    dependsOn("testDebugUnitTest", "connectedDebugAndroidTest")

    //Configure output formats
    reports {
        xml.required.set(true) // XML -> required for SonarQube
        html.required.set(true) //HTML -> visual coverage report
    }

    // Exclude auto-generated or irrelevant files from coverage
    val fileFilter = listOf(
        "**/R.class", // Android resources classes
        "**/R$*.class", // Nested resources classes
        "**/BuildConfig.*", // Auto-generated BuildConfig
        "**/Manifest*.*", // Manifest-generated files
        "**/*Test*.*", // Exclude test classes
        "android/**/*.*" //Android framework classes
    )

    //Kotlin compiled classes for debug build
    val kotlinClasses = fileTree(layout.buildDirectory.dir("tmp/kotlin-classes/debug")) {
        exclude(fileFilter)
    }

    //Java compiled classes for debug build
    val javaClasses = fileTree(layout.buildDirectory.dir("intermediates/javac/debug")) {
        exclude(fileFilter)
    }

    // Compiled Kotlin + Java class directories
    classDirectories.setFrom(files(kotlinClasses, javaClasses))

    // Tell JacoCo where your actual source code lives
    sourceDirectories.setFrom(files("src/main/java", "src/main/kotlin"))

    //Point to the JaCoCo execution data generated by unit tests and instrumented tests
    executionData.setFrom(fileTree(layout.buildDirectory) {

        include(
            // Unit test coverage
            "outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec",

            // Instrumented test coverage
            "outputs/code_coverage/debugAndroidTest/connected/**/*.ec"
        )
    }
    )
}